scrape_dbt:
  outputs:
    dev:
      dataset: TestScrapeDataset
      job_execution_timeout_seconds: 30
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dagstertest-382218
      threads: 1
      type: bigquery
  target: dev
scrape_project_dbt:
  outputs:
    dev:
      dataset: TestScrapeDataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dagstertest-382218
      threads: 1
      type: bigquery
  target: dev